zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
    KAFKA_CREATE_TOPICS:  "pipeline_success:1:1,pipeline_failure:1:1,pipeline_command:1:1,pipeline_status:1:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
